### DISCUSSION TITLE
Filtering the logs

### DISCUSSION THREAD

**Discussion by M4RC02U1F4A4** [signalfx/splunk-otel-collector-chart#1132] [Q&A] [answered]
Hello,
is it possible to filter logs in a way that avoids importing too many events to Splunk?
In particular, I would like to import only the logs that match a given regex

Thanks,
Marco

**Comment by M4RC02U1F4A4** [comment, marked as answer]
It is possible to filter the logs by going to edit the configuration of OpenTelemtry Collector from here https://github.com/signalfx/splunk-otel-collector-chart/blob/22aa7e493acd797d2d8edfdb002d67bf92a8e7d3/helm-charts/splunk-otel-collector/values.yaml#L433

Below is an example of a conf that collects only logs beginning with `INFO`

```yaml
agent:
  config:
    processors:
      filter/severity_text:
        logs:
          include:
            match_type: regexp
            bodies:
            - ^INFO
            resource_attributes:
            - key: k8s.container.name
              value: test-log-container
    service:
      pipelines:
        logs:
          processors:
          - memory_limiter
          - k8sattributes
          - filter/logs
          - batch
          - resourcedetection
          - resource
          - resource/logs
          - resource/add_environment
          - filter/severity_text
```
