### DISCUSSION TITLE
Please add readiness and liveness probe params to the otel-collector's template

### DISCUSSION THREAD

**Discussion by nkbud** [signalfx/splunk-otel-collector-chart#1428] [Ideas]
Please add controls for the readiness and liveness probes. 
I was unable to push my branch or create an issue (no splunk login...), perhaps we can solve that.  

Here is the requested code change, where you can see we're just adding controls for these parameters.

daemonset.yaml

from:
```
        readinessProbe:
          {{- if .Values.readinessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
        livenessProbe:
          {{- if .Values.livenessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
```
to:
```
        readinessProbe:
          {{- if .Values.readinessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.periodSeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.failureThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
        livenessProbe:
          {{- if .Values.livenessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.periodSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.failureThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
```

values.yaml

from:
```
# This tells the kubelet that it should wait for x seconds before performing the first probe.
# This is required in case you are using windows worker nodes.
# It is recommended to keep it a 60-second window but it depends on cluster specification.
readinessProbe:
  initialDelaySeconds: 0
livenessProbe:
  initialDelaySeconds: 0
```

to:
```
# initialDelaySeconds: This tells the kubelet that it should wait for x seconds before performing the first probe.
# This is required in case you are using windows worker nodes.
# It is recommended to keep it a 60-second window but it depends on cluster specification.
# periodSeconds: The frequency (in seconds) with which the probe should be performed.
# failureThreshold: The number of consecutive probe failures before the pod is marked as Unready.
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  failureThreshold: 3
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  failureThreshold: 3
```

We're experiencing regular but infrequent pod restarts due to liveness probe failures, and would like to increase those values higher than their defaults. 

I would prefer to push a branch and make a pull request. Please do lmk if there's an easy way to do that.
