### DISCUSSION TITLE
Unable to collect events and k8s objects on Openshift

### DISCUSSION THREAD

**Discussion by Mojito2110** [signalfx/splunk-otel-collector-chart#1502] [Q&A]
Hi,

I have deployed the chart splunk otel collector version 0.102.0 in a cluster Openshift. The goal is to collect application logs (it's ok) and the events Kubernetes. 
I apply the settings following the documentation of the chart helm but the events don't be gathered

the settings  in the values.yaml are below : 
 ```
splunkPlatform:
  endpoint: "https://*******/services/collector"
  token: "a37**********"
  index: "******"
  logsEnabled: true

rbac:
  customRules: 
    - apiGroups:
      - "events.k8s.io"
      resources:
      - events
      verbs:
      - get
      - list
      - watch
  
distribution: "openshift"

clusterReceiver:
  enabled: true
  k8sObjects:
    - name: pods
      mode: pull
      interval: 5m
    - name: events
      mode: watch
      group: events.k8s.io

agent:
  enabled: true
    service:
      pipelines:
        logs:
          processors:
            - memory_limiter
            - k8sattributes
            - filter/logs
            - batch
            - resourcedetection
            - resource
            - resource/logs
 ```

Could you help me ?
Kind regards
