### DISCUSSION TITLE
k8sattributes/metrics unable to pull metadata k8s.namespace.name and k8s.pod.name

### DISCUSSION THREAD

**Discussion by gurpartb** [signalfx/splunk-otel-collector-chart#1531] [General]
I've .net application instrumented with Opentelemetry Libraries running on AKS using istio service mesh. k8sattributes processor already pulls in metadata k8s.pod.name and k8s.namespace.name and enriches the log data. I updated the k8sattributes/metrics processor to pull in metadata as well.
```yaml
        processors:
          k8sattributes/metrics:
            extract:
              metadata:
              - k8s.namespace.name
              - k8s.pod.name
```
This alone didn't' work for me. I then had to move the k8sattributes processor up in the service.pipeline.metrics above the batch processor to match the placement of k8ssattributes processor in service.pipeline.logs and that worked.
```yaml
        service:
          pipelines:
            metrics:
              processors:
                - memory_limiter
                - k8sattributes/metrics
                - batch
                - attributes/istio
                - resourcedetection
                - resource
```
I don't know what the issues maybe and I didn't try other variations. Feel free to validate it. It might help someone else.
