### DISCUSSION TITLE
Please support topology spread constraints on the gateway deployment

### DISCUSSION THREAD

**Discussion by amccague** [signalfx/splunk-otel-collector-chart#1750] [Ideas] [answered]
I am expecting to be able to configure topology spread constraints via the chart https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

There is currently no facility to add arbitrary configurations to the pod spec, following the current approach this requires the following value default:

```yaml
gateway:
    affinity: {}
    topologySpreadConstraints: []
```
