### DISCUSSION TITLE
Add an example of how to configure `extraOperators`

### DISCUSSION THREAD

**Discussion by matthewmodestino** [signalfx/splunk-otel-collector-chart#524] [General]
I have an OTel native logging user that wants to set different index values for logs emitted from a single pod. 

I believe setting `extraOperators` should allow them to set `router` example to match a value then route to another operator that will set the index value. 

Could use an example of how to set something like that here:

https://github.com/signalfx/splunk-otel-collector-chart/blob/75cfd0b637fee138191bf48b7cb323d1440b70c4/helm-charts/splunk-otel-collector/values.yaml#L424-L425

**Comment by matthewmodestino** [comment]
After reviewing the `extraOperators` helm templates, we will likely need to adjust the log pipeline to insert rendered `extraOperators` above the multiline recombine rules, or insert custom `routes` to direct to the custom operators, then to the multiline operator blocks. otherwise they will not be reached by events moving through the pipeline:

https://github.com/signalfx/splunk-otel-collector-chart/blob/8bbb83411fe8665b6322704ff4632504a2dac1e9/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L345-L363

Currently in testing adding custom Operators to deal with the user need to set index on events in a single log, I am editing the configmap directly. 

Will also likely need to expose options for `processors` as well to customize outcomes customers may need.

**Comment by matthewmodestino** [comment]
Here's an example of how I used `extraOperators` to slide in a custom `recombine` rule for docker truncated events:

```
    extraOperators:
      - combine_field: log
        id: docker-recombine
        is_last_entry: ($$.log) endsWith "\n"
        type: recombine
        source_identifier: $$resource["com.splunk.source"]
        combine_with: ""
```
