### DISCUSSION TITLE
Need some help in enabling smartagent in the ClusterReceiver section

### DISCUSSION THREAD

**Discussion by govardha** [signalfx/splunk-otel-collector-chart#622] [Q&A] [answered]
Hello,

I am new to both k8s & configuring otel, I have made a lot of progress, but I am stumbling on a few issues.  I am using the helm chart to deploy agents/receiver across my cluster.

As I was reading through the documentation I stumbled on this which has a lot of useful stuff identical to kube-state-metrics

https://github.com/signalfx/signalfx-agent/blob/main/docs/monitors/kubernetes-cluster.md#kubernetes-cluster

I wanted to add this receiver and I configured the section in

clusterReceiver.config.receivers

```
smartagent/kubernetes-cluster
  config:
    type: kubernetes-cluster
    extraDimensions:
     metrics_source: kube-state-metrics
  intervalSeconds: 60
  kubernetesAPI:
    authType: useServiceAccount
```

Although I have made sure `type` is identified, otel keeps complaining, you must specify a "type" for a smartagent receiver.  

Can I not use any of the smartagents listed in the page [monitor link](https://github.com/signalfx/signalfx-agent/blob/main/docs/monitor-config.md)

What am I doing wrong here?  

Thank you!

**Comment by atoulme** [comment, marked as answer]
It looks like a whitespace indenting issue. Please let us know if you managed to fix this.

**Reply by govardha** [reply]
I got this working.  The settings to get a generic smartagent/module working is to configure it as a `receiver` as shown below, and then creating a brand new pipeline.  I further had to clean up some attributes.  

```
        smartagent/kubernetes-cluster:
          type: kubernetes-cluster
          intervalSeconds: 60
          extraDimensions:
            metric_source: kube-state-metrics
          alwaysClusterReporter: true
          kubernetesAPI:
            authType: serviceAccount
```

That said, I realized the opentelemetry package already has support for this in a contrib module [k8scluster](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver).  I am now getting all the metrics that package kube-state-metrics provides into my splunk enterprise instance.
