### DISCUSSION TITLE
Enabling K8s cluster receiver

### DISCUSSION THREAD

**Discussion by atsikham** [signalfx/splunk-otel-collector-chart#672] [Q&A] [answered]
Hi Team,

Could anyone help me with the following issue? I’m installing splunk-otel-collector on EKS via Helm [chart](https://github.com/signalfx/splunk-otel-collector-chart) and trying to configure additional K8s metrics, such as `kubernetes.stateful_set.updated`. For that, there is an additional receivers configuration like it’s in the doc - https://docs.splunk.com/Observability/gdi/opentelemetry/components/kubernetes-cluster-receiver.html#configuration, but not all the metrics are still visible via metrics finder.

Chart values:

```
clusterName: ${cluster_name}
splunkObservability:
  realm: ${realm}
  accessToken: ${signalfx_token}
cloudProvider: aws
distribution: eks
environment: ${environment}
agent:
  config:
    receivers:
      kubeletstats:
        metric_groups:
        - container
        - pod
        - node
        - volume
      k8s_cluster:
        auth_type: serviceAccount
        collection_interval: 30s
        node_conditions_to_report: ["Ready", "MemoryPressure"]
        allocatable_types_to_report: ["cpu","memory"]
        metadata_exporters: [signalfx]
      receiver_creator:
        receivers:
          prometheus_simple/plaintext:
            config:
              endpoint: '`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"] : 9090`'
              metrics_path: /metrics
            rule: type == "pod" && annotations["prometheus.io/export-to-signalfx"] == "true"
          smartagent/coredns:
            config:
              port: 9153
              type: coredns
            rule: type == "pod" && labels["k8s-app"] == "kube-dns"
    service:
      telemetry:
        logs:
          level: warn
  maxUnavailable: 20%
  resources:
   limits:
     memory: ${agent_memory_limit}
   requests:
     cpu: 40m
     memory: 200Mi
clusterReceiver:
  resources:
   limits:
     memory: ${receiver_memory_limit}
   requests:
     memory: ${receiver_memory_request}
serviceAccount:
  create: true
  name: ${service_account_name}
```
