### ISSUE TITLE
Multiline Config not applied

### ISSUE THREAD

**Issue by LarsWinters** [signalfx/splunk-otel-collector-chart#1008]
Hi all, 

we try to set a MultiLineConfig for all Namespaces, Pods and Containers. It should use Multiline for all logs starting with "Caused by" or a leading whitespace. The config looks like this:
```
multilineConfigs:
      - namespaceName:
          value: .*
        podName:
          value: .*
          useRegexp: true
        containerName:
          value: .*
        firstEntryRegex: ^(?:\s|Caused by)
```
If I put this regex in regex101 and test it with a Log it works just fine. I suppose it doesn't apply correctly. Is the wildcard .* valid?
Or any other ideas why it doesn't work?
Best regards

**Comment by atoulme** [comment]
You might need to set `useRegexp` on the other fields:
```
multilineConfigs:
      - namespaceName:
          value: .*
          useRegexp: true
        podName:
          value: .*
          useRegexp: true
        containerName:
          value: .*
          useRegexp: true
        firstEntryRegex: ^(?:\s|Caused by)
```
