### ISSUE TITLE
No labels attributes in metric data to Splunk Enterprise

### ISSUE THREAD

**Issue by Ronnybrouwers** [signalfx/splunk-otel-collector-chart#1013]
We are sending metrics over HEC to Splunk Enterprise, but missing the pod labels in the data dimensions. Especially looking for the app labels.

in the docs (values.yaml) I see that Pod labels always should sent:

_IMPORTANT: Additional attributes configured with `fromLabels` and `fromAttributes` options are only applied to traces and logs. Pod labels are # always sent to Splunk Observability (if enabled) as metric properties._

For pod metrics we're only receiving the following dimensions currently:

cluster_name
k8s.cluster.name
k8s.namespace.name
k8s.node.name
k8s.pod.name
k8s.pod.uid
os.type

Do I need to tweak some settings?

**Comment by omrozowicz-splunk** [comment]
Hey, do I understand it right that you want to see all the pod labels as a metric dimension? 
This is not included by default, you can use `extraAttributes.fromLabels`, but then you need to explicitly set what `label` you want to gather from pods.

`Pod labels are # always sent to Splunk Observability (if enabled) as metric properties.` - this works for Splunk Observability, and as I understand you want to send your metrics to Splunk Enterprise. For Splunk Enterprise it doesn't work this way.

**Comment by Ronnybrouwers** [comment]
Correct, I want to see the pod labels as metric dimensions.

I've indeed tested the extraAttributes.fromLabels, but sadly this only applies to the logs data and not my metrics:
_IMPORTANT: Additional attributes configured with fromLabels and fromAttributes options are only applied to traces and logs_

**Comment by omrozowicz-splunk** [comment]
Oh, right. Would overwriting the metrics pipeline be a way to go? I mean to do what we have under the hood for `fromLabels` for logs. It requires the creation of another processor and putting it under metrics. For the default settings with Splunk Enterprise it'd be:

```
agent:
  config:
    processors:
      k8sattributes/2:
        auth_type: "serviceAccount"
        filter:
          node_from_env_var: KUBE_NODE_NAME
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: ip
        - sources:
          - from: connection
        - sources:
          - from: resource_attribute
            name: host.name
        extract:
          labels:
            - key: app
    service:
      pipelines:
        metrics:
          processors:
          - memory_limiter
          - batch
          - resourcedetection
          - resource
          - k8sattributes/2
        metrics/agent:
          processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resourcedetection
          - resource
          - k8sattributes/2
```

to enrich metric events from `agent` pod with `k8s.pod.label.app`
