### ISSUE TITLE
Enabled Metrics causes the cluster to crash

### ISSUE THREAD

**Issue by xxPhuNguyenxx** [signalfx/splunk-otel-collector-chart#1018]
### What happened?
**Description**

We're seeing the following error shortly after updating the values.yaml file to enable metrics, followed by a helm update. The cluster runs for less than 1 min then proceeds to crash

20s         Warning   Unhealthy           pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Readiness probe failed: Get "[http://10.129.xxx.xxx:13133/":](http://10.12x.x.xxx:13133/%22:) dial tcp 10.129.xxx.xxx:13133: connect: connection refused
19s         Warning   Unhealthy           pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Readiness probe failed: HTTP probe failed with statuscode: 503
37s         Warning   BackOff             pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Back-off restarting failed container
4m22s       Normal    Killing             pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverhqjx8                Stopping container otel-collector

-bash-4.2$ oc logs ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7
Error from server: Get "[https://30.11x.xx.xxx:10250/containerLogs/splunk-otel/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7/otel-collector":](https://30.11x.xx.xxx:10250/containerLogs/splunk-otel/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7/otel-collector%22:) remote error: tls: internal error

-bash-4.2$

### Steps to Reproduce
1) Update  metricsEnabled value to be true, we were expecting to see metrics log. everything runs normal for less than 1 min before crashing
metricsEnabled: true

as soon as we revert the to be metricsEnabled value to be false, everything works as normal again
metricsEnabled: false

### Expected Result
see metrics logs from cluster in splunk

### Actual Result
cluster crash 

Chart version
 

### Environment information
Environment
ocp on premise

**Chart configuration**
 below is our values.yaml
```
agent:
  config:
    processors:
      filter/exclude_all_telemetry_data_from_namespace:
        logs:
          exclude:
            match_type: regexp
            resource_attributes:
            - key: k8s.namespace.name
              value: ^(datadog)$
        metrics:
          exclude:
            match_type: regexp
            resource_attributes:
            - key: k8s.namespace.name
              value: ^(datadog)$
        traces:
          span:
          - attributes["k8s.namespace.name"] != "datadog"
    service:
      pipelines:
        logs:
          processors:
          - filter/exclude_all_telemetry_data_from_namespace
  resources:
    limits:
      cpu: 1
      memory: 2Gi
cloudProvider: ""
clusterName: onprem-sbx-env
distribution: openshift
environment: sandbox
logsEngine: otel
clusterReceiver:
  k8sObjects:
    - name: pods
      mode: pull
      interval: 5m
    - name: namespaces
      mode: pull
      interval: 5m
    - name: nodes
      mode: pull
      interval: 5m 
    - name: events
      mode: watch
      group: events.k8s.io
logsCollection:
  containers:
    excludePaths: ["/var/log/pods/datadog_datadog-*/*/*.log"]
    excludeAgentLogs: false
    multilineConfigs:
    - namespaceName:
        value: splunk-otel
      podName:
        value: ocp4-onprem-sbx-splunk-otel-*
        useRegexp: true
      firstEntryRegex: ^([\r\n]+)*\d{4}\-\d{2}\-[0-9T]{3,5}\:\d{2}\:\d{2}\.[0-9Z]{4}.*

  extraFileLogs:
    filelog/audit-log:
      include: [/var/log/kube-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/kube-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
    filelog/oauth-audit:
      include: [/var/log/oauth-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/oauth-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
    filelog/openshift-audit:
      include: [/var/log/openshift-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/openshift-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
splunkPlatform:
  disableCompression: false
  endpoint: https://HEC-VIP/services/collector/event
  idleConnTimeout: 30s
  index: SCKL_CAAS_auto
  insecureSkipVerify: true
  logsEnabled: true
  maxConnections: 200
  metricsEnabled: true
  metricsIndex: metric_index
  retryOnFailure:
    enabled: true
    initialInterval: 30s
    maxElapsedTime: 600s
    maxInterval: 60s
  timeout: 60s
  token: xxxx-xxx-xxx-xxx-xxxxxxxxxxxx
  tracesEnabled: false
```

### Log output
 20s         Warning   Unhealthy           pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Readiness probe failed: Get "[http://10.129.xxx.xxx:13133/":](http://10.12x.x.xxx:13133/%22:) dial tcp 10.129.xxx.xxx:13133: connect: connection refused
19s         Warning   Unhealthy           pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Readiness probe failed: HTTP probe failed with statuscode: 503
37s         Warning   BackOff             pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7                Back-off restarting failed container
4m22s       Normal    Killing             pod/ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverhqjx8                Stopping container otel-collector

Additional context

**Comment by rmfitzpatrick** [comment]
@xxPhuNguyenxx thanks for your report. I don't believe we have enough information and your environment may have a configuration issue that's preventing you from providing helpful logs (maybe [`oc adm certficate approve`](https://docs.openshift.com/container-platform/4.5/cli_reference/openshift_cli/administrator-cli-commands.html#certificate)?). I believe opening a [support case](https://splunk.my.site.com/customer/s/need-help/create-case) will provide more through assistance than we can provide in a github issue.

**Comment by xxPhuNguyenxx** [comment]
@rmfitzpatrick  what info do you need that's missing? Also, i'll put in a support case now for it

**Comment by rmfitzpatrick** [comment]
I believe your `oc logs ocp4-onprem-sbx-splunk-otel-collector-k8s-cluster-receiverbb9k7` invocation is failing to show the actual collector logs that would be required to show any startup issues the health check extension's failed probes suggest are occurring.

**Comment by xxPhuNguyenxx** [comment]
fyi ive in ticket 3357968

**Comment by VihasMakwana** [comment]
@xxPhuNguyenxx This error is reproducible on my end and the issue here in my case was limited resources allocated.
I see you have increased the resources for agents.
I would suggest the same for clusterReceiver.
You can do like following in values.yaml:

```
clusterReceiver:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
```

Also, please monitor the logs of the cluster receiver while it’s running. Attach the logs if it behaves weirdly.
You can also see why it was killed by doing:
`kubectl describe pod POD_NAME` and examining `Last State` field.
