### ISSUE TITLE
Certificate verification issue while enabling metrics and trace type of log data for AKS cluster

### ISSUE THREAD

**Issue by ajaykumarrc** [signalfx/splunk-otel-collector-chart#1088]
### Discussed in https://github.com/signalfx/splunk-otel-collector-chart/discussions/1087

<div type='discussions-op-text'>

<sup>Originally posted by **ajaykumarrc** December 18, 2023</sup>

i have installed splunk otel connector on AKS cluster version **1.25.15**  after enabling metric type logs am getting the below error any workaround for the below error.

`error   kubeletstatsreceiver@v0.91.0/scraper.go:77      call to /stats/summary endpoint failed  {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://1xx.2xx.xx.xxx:10250/stats/summary\": tls: failed to verify certificate: x509: cannot validate certificate for 1**.2***.**.**03 because it doesn't contain any IP SANs"}`

</div>

**Comment by omrozowicz-splunk** [comment]
Hey, 
I haven't seen this issue so far, but this comes from the [kubeletstats](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) receiver. You can check the docs to check how to configure `tls`. I think as a dirty workaround I'd try to overwrite it first with the following config:

```
agent:
  config:
    kubeletstats:
      auth_type: serviceAccount
      insecure_skip_verify: true
      collection_interval: 10s
      endpoint: ${K8S_NODE_IP}:10250
      extra_metadata_labels:
      - container.id
      metric_groups:
      - container
      - pod
      - node
```

This is the default config with ` insecure_skip_verify: true` option
