### ISSUE TITLE
Add option to collect volume metrics from kubeletstats receiver

### ISSUE THREAD

**Issue by asuresh4** [signalfx/splunk-otel-collector-chart#111]
The `kubeletstats` receiver optionally collects volume metrics. Add an option to configure the receiver to collect these metrics. This will give us parity with the [SA chart](https://github.com/signalfx/signalfx-agent/blob/v5.9.2/deployments/k8s/helm/signalfx-agent/values.yaml#L267).

**Comment by dmitryax** [comment]
It is possible to configure any component in the chart. To configure `kubeletstats` receiver you have the following option:
```
otelAget:
  config:
    receivers:  
      kubeletstats:
        <any kubeletstats config overrides>
```
Isn't it sufficient? Or do we want volume metrics enabled by default?
