### ISSUE TITLE
It should be possible to add custom labels to the deployments

### ISSUE THREAD

**Issue by debae** [signalfx/splunk-otel-collector-chart#156]
We for example determine on specific labels in a deployment where a pod should be running, on a specific node , on fargate ...
It is however not possible to add custom labels and/or annotations to the template of the pod : 
```
  template:
    metadata:
      labels:
        app: {{ template "splunk-otel-collector.name" . }}
        component: otel-k8s-cluster-receiver
        release: {{ .Release.Name }}
```

Ideally we should have something like this :

```
  template:
    metadata:
      labels:
        app: {{ template "splunk-otel-collector.name" . }}
        component: otel-k8s-cluster-receiver
        release: {{ .Release.Name }}
        {{- if .Values.podLabels }}
        {{- with .Values.podLabels}}
        {{ toYaml . | indent 8 }}
        {{- end }}
        {{- end }}
```
