### ISSUE TITLE
Support for secret for both splunkPlatform and splunkObservability

### ISSUE THREAD

**Issue by byronmansfield** [signalfx/splunk-otel-collector-chart#1676]
Maybe I'm missing how I can achieve this. But I would like to send logs and metrics to Splunk O11y. I got some errors `splunkObservability.logsEnabled: true`. Then I was informed that was because I need to send logs to `splunkPlatform`. However, `splunkPlatform` requires a hec token and `splunkObservability` requires an access-token. So they are not equal to the same thing. The `secret` is an object, not an array of secretes. Therefore I can only set one of them.

**Proposal**

```yaml
splunkPlatform:
  ...
splunkObservability:
  ...
secrets:
  - access-token:
    name: "access-token"
  - hec-token:
    name: "hec-token"
```

Of something similar to this. As long as we can have both with individual secrets or even in the same secret, but with different keys maybe.
