### ISSUE TITLE
receivercreator not appending custom resource_attributes

### ISSUE THREAD

**Issue by andreas-ahman** [signalfx/splunk-otel-collector-chart#188]
I'm trying to add some attributes to metrics being scraped.

```yaml
receiver_creator:
  receivers:
    prometheus_simple:
      config:
        endpoint: '`endpoint`:`"agent.signalfx.com/port" in labels ? labels["agent.signalfx.com/port"] : 9090`'
        metrics_path: '`"agent.signalfx.com/metric_path" in annotations ? annotations["agent.signalfx.com/metric_path"] : "/metrics"`'
      resource_attributes:
        kubernetes_cluster: mycluster
      rule: type == "pod" && labels["agent.signalfx.com/scrape"] == "true"
`
```

These additional attributes does however not show up in the metric.

Why does it not show up and if it's intentional how can I add custom dimensions on the metrics?
