### ISSUE TITLE
Support for Istio VirtualService resource

### ISSUE THREAD

**Issue by tknguyen3** [signalfx/splunk-otel-collector-chart#293]
It would be nice to have native support for Istio VirtualService resources that get deployed along with everything else. We used to modify `values.yaml` directly but ever since this [schema validation change](https://github.com/signalfx/splunk-otel-collector-chart/pull/239), we now get the following error.

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- (root): Additional property virtualService is not allowed
```
Flipping `additionalProperties` back to false would be an option, but something that would need to be re-applied after every upgrade.

For reference, here's a simplified example of a `VirtualService` template and struct that would go in `values.yaml`:

**virtual-service.yaml template**
```
{{ if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: splunk-otel-collector
  name: splunk-otel-collector
spec:
  {{- with .Values.virtualService.gateways }}
  gateways:
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}

  {{- with .Values.virtualService.hosts }}
  hosts:
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}

  {{- with .Values.virtualService.http }}
  http:
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}
{{- end}}
```

**values.yaml**
```
virtualService:
  enabled: true
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - splunk-otel-collector.example.com
  http:
  - match:
    - uri:
        prefix: /v2/datapoint
    route:
    - destination:
        host: splunk-otel-collector
        port:
          number: 9943
  - route:
    - destination:
        host: splunk-otel-collector
        port:
          number: 4317
```
