### ISSUE TITLE
Resource Detection Processor fails to retrieve configmap "aws_auth" on EKS

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#427]
When deploying on EKS (both linux and windows nodes) the OTel collector agent warns it is unable to retrieve `aws-auth` configmap. 

```
2022-04-01T23:03:58.299Z	warn	internal/resourcedetection.go:131	failed to detect resource	{"kind": "processor", "name": "resourcedetection", "pipeline": "logs", "error": "isEks() error retrieving auth configmap: failed to retrieve ConfigMap kube-system/aws-auth: configmaps \"aws-auth\" is forbidden: User \"system:serviceaccount:otel:mattymo-splunk-otel-collector\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}
```

Working with a customer, I believe they had to add `ConfigMap` to the `ClusterRole` to get the warns to go away. 

https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/clusterRole.yaml

**Comment by mbranyon** [comment]
I am seeing this issue exact issue as well.

**Comment by wpgrant** [comment]
I have another customer hitting this. Is this something that needs to be fixed in the chart? Or do we need to add something to the docs about it?

**Comment by omrozowicz-splunk** [comment]
I think what fixes this issue is configuring:
```
rbac:
  customRules:
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - list
        - watch
```
