### ISSUE TITLE
Issues deploying on EKS Windows Nodes

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#428]
Hi team, in working with a user deploying to EKS Windows Node Groups, we ran into a few items that caused the deployment to fail using default chart values. 

In order to deploy successfully we needed to make customizations to the chart, that like should be done by default, or included in documentation:

Update SecurityContext:

We had to update security context to use `ContainerAdministrator` user for windows. 

```
 # To collect container logs and journald logs, it will run the agent as a root user.
  # To run it as non root user, uncomment below `securityContext` options.
  # Setting runAsUser and runAsGroup to a non root user enables an init container that patches group
  # permissions of container logs directories on the host filesystem to make logs readable by this non root user.

  securityContext:
    windowsOptions:
      runAsUserName: ContainerAdministrator 
```

Then we had to create a new secret to not step on the old one. Although I assume in docs we could advise how to point to the existing one already created by first deploying the linux chart...

```
secret:
  create: true
  name: "splunk-otel-collector-windows"
  # Specifies whether secret provided by user should be validated.
  validateSecret: true
```

**Comment by halovanic** [comment]
Thank you @matthewmodestino, I too had been struggling to make Windows on EKS work since 0.42 and this magic `agent.securityContext` value is indeed the fix.  It seems this should either be incorporated into the Windows documentation or keyed off the `isWindows` value since I don't think any other security options work under Windows.

I think the general direction for the secret problem is to fully deploy the collector chart twice, once for Linux and once for Windows (assuming you have both kinds of nodes).  That's most easily done by using a different namespace like "splunk-win", so this conflict won't happen and you can just manage them separately.

I also found that the default agent memory limit was just a bit too low under Windows to work reliably, although YMMV.

**Comment by matthewmodestino** [comment]
That's another good point, I did find that both the liveness probe guidance in the chart was key, and did see instances where upping the resource limits was helpful. 

```
# This tells the kubelet that it should wait for x seconds before performing the first probe.
# This is required in case you are using windows worker nodes.
# It is recommended to keep it a 60-second window but it depends on cluster specification.
readinessProbe:
  initialDelaySeconds: 0
livenessProbe:
  initialDelaySeconds: 0
```
