### ISSUE TITLE
Invalid configuration: either “log_data_enabled” or “profiling_data_enabled” has to be true

### ISSUE THREAD

**Issue by aquam8** [signalfx/splunk-otel-collector-chart#456]
Hi

I would like to report a problem. It's related to #444 I think . I did not have that problem in version 0.48.0 of the Helm chart.

In 0.51.0 it now complains with this error:
```
main.go:136: application run finished with error: failed to get config: invalid configuration: exporter “splunk_hec/o11y” has invalid configuration: either “log_data_enabled” or “profiling_data_enabled” has to be true
```

I can confirm that both log and profiling is disabled in my case, but why does any has to be enabled. I only want to have metrics and traces to be sent to o11y because of data governance restrictions.

I would like to see that no errors are raised when both log and profiling are disabled. Would that be possible?

Thank you

**Comment by rmfitzpatrick** [comment]
Thanks for your report @aquam8. The validation error was introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6e1dcf6c37cd68d52a96523aa463f1ed0760358e and I think the changes in #444 may expose that we could be using the wrong helper value for determining whether to enable the exporter for the agent and cluster receiver configurations. However, on first inspection I think I'm seeing this path as possible when the deprecated root `--set logsEnabled=true` and the newer conflicting `--set splunkObservability.logsEnabled=false` values are set. Using `splunkObservability.logsEnabled=false,splunkPlatform.logsEnabled=true` should be the desired config.

Are you able to share the values you're using and the container type that's throwing the validation error?

**Comment by aquam8** [comment]
Hi @rmfitzpatrick 

I am indeed using the values you listed `splunkObservability.logsEnabled=false, splunkPlatform.logsEnabled=true`.
See my Helm values:
```
autodetect:
  prometheus: false
clusterName: XXX
clusterReceiver:
  k8sEventsEnabled: true
distro: eks
gateway:
  enabled: false
logsEngine: otel
provider: aws
splunkObservability:
  accessToken: XXX
  logsEnabled: false
  metricsEnabled: true
  profilingEnabled: true
  realm: us1
  tracesEnabled: true
splunkPlatform:
  endpoint: XXX
  index: XXX
  logsEnabled: true
  metricsEnabled: false
  token: XXX
```

The error comes  from `splunk-otel/splunk-otel-collector-chart-k8s-cluster-receiver` deploy/pod:
```
2022/06/07 05:41:59 main.go:269: Set config to /conf/relay.yaml
2022/06/07 05:41:59 main.go:352: Set ballast to 165 MiB
2022/06/07 05:41:59 main.go:366: Set memory limit to 450 MiB
Error: failed to get config: invalid configuration: exporter "splunk_hec/o11y" has invalid configuration: either "log_data_enabled" or "profiling_data_enabled" has to be true
2022/06/07 05:42:00 main.go:136: application run finished with error: failed to get config: invalid configuration: exporter "splunk_hec/o11y" has invalid configuration: either "log_data_enabled" or "profiling_data_enabled" has to be true
Stream closed EOF for splunk-otel/splunk-otel-collector-chart-k8s-cluster-receiver-5bc754fc4tp8kk (otel-collector)
```

The `splunk-otel/splunk-otel-collector-chart-agent` daemonset starts okay.

Changing `splunkObservability.logsEnabled: true` fixes the problem - but it's not possible for me to enable for geolocation constraints at the moment.

Thank you!
