### ISSUE TITLE
Splunk events split with linebreak at 8k

### ISSUE THREAD

**Issue by wiika** [signalfx/splunk-otel-collector-chart#458]
We have installed the splunk-otel-collector-chart on Openshift on Azure (ARO) using ArgoCD. Long log lines are split at 8k (8192 characters) and appear in Splunk with a linebreak/newline at the split point. I have read that splitting at 8k is standard on Openshift/Kubernetes by crio:
https://access.redhat.com/solutions/5675451
https://access.redhat.com/solutions/5823701

Markers are inserted to indicate that the file has been split, I see this in the raw log files on the Openshift nodes. The problem is that when the files are joined there seems to be a newline inserted.

Example:
This is from the raw log file in Openshift:
```
2022-05-31T08:15:14.038113456+00:00 stdout P {"@timestamp":"2022-05-31T08:15:14.037Z","log.level":"ERROR","message":"rcid=ab2e2239-3aee-4993-b376-5a149160f549 Feil ved behandleOrdre() ", "ecs.version": "1.2.0", ... \n\tat org.glassfish.jersey.servlet.ServletContain
2022-05-31T08:15:14.038176457+00:00 stdout F er.service(ServletContainer.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)\n\tat ...

```
The P indicates a Primary line in the split and F is the final piece. I have shortened the log at the ... locations but the first logline is exactly 8192 characters long.

This is what we see in Splunk Cloud:
![image](https://user-images.githubusercontent.com/1029451/171399267-99436013-16d5-45cd-99c3-b178787bd0d8.png)

This is our ArgoCD Helm yaml:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk
spec:
  ignoreDifferences:
  - name: splunk-splunk-otel-collector-eika
    kind: SecurityContextConstraints
    group: security.openshift.io
    jsonPointers:
    - /allowedFlexVolumes
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    chart: splunk-otel-collector
    repoURL: https://signalfx.github.io/splunk-otel-collector-chart
    targetRevision: 0.51.0
    helm:
      parameters:
      - name: agent.resources.limits.memory
        value: 2Gi
      - name: nameOverride
        value: "splunk-otel-collector-eika"
      - name: clusterName
        value: "aro-backend-dev1"
      - name: splunkPlatform.endpoint
        value: "https://http-inputs-eika.splunkcloud.com/services/collector"
      - name: splunkPlatform.token
        value: "xxx"
      - name: splunkPlatform.index
        value: "aro-backend-dev1"
      - name: logsEngine
        value: otel
      - name: cloudProvider
        value: azure
      - name: distribution
        value: openshift
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

Any missing config we should add? Other ideas?
