### ISSUE TITLE
Move system option for agent from the top level

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#474]
The following options are defined in the top level but applicable only for the agent. Other components have the same options at their own levels:

```yaml
# This default tolerations allow the daemonset to be deployed on master nodes,
# so that we can also collect logs and metrics from those nodes.
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

# Defines which nodes should be selected to deploy the o11y collector daemonset.
nodeSelector: {}
terminationGracePeriodSeconds: 600

# Defines node affinity to restrict deployment of the o11y collector daemonset.
affinity: {}

# Defines priorityClassName to assign a priority class to pods.
priorityClassName: ""
```

They should be moved under `agent` for consistency with other components. We should support both places for a while, so the change should be done in backward compatible way with a warning if the root level configs are being used.
