### ISSUE TITLE
Docker default `recombine` operator is skipped 

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#627]
Hey Team!

While troubleshooting why our default docker recombine rule was not reassembling partial docker logs from AKS, it was found that our pipeline definition skips it. We originally added it here https://github.com/signalfx/splunk-otel-collector-chart/pull/467. We need to update the Docker JSON parser operator to ensure it passes the parsed logs to the recombine rule:

```
    operators:
        - id: parser-docker
          output: handle_empty_log
          timestamp:
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'
            parse_from: attributes.time
          type: json_parser
        - combine_field: attributes.log
          combine_with: ""
          id: docker-recombine
          is_last_entry: attributes.log endsWith "\n"
          output: handle_empty_log
          source_identifier: attributes["log.file.path"]
          type: recombine
        - field: attributes.log
          id: handle_empty_log
          if: attributes.log == nil
          type: add
          value: ""

```

We need to update the output value in the `parser-docker` to emit to the `docker-recombine` and not directly to `handle_empty_log` OR insert the `docker-recombine` AFTER the `handle_empty_log`. 

Either way should solve the issue. 

Thanks team!
