### ISSUE TITLE
Issues on 0.67.0 on Windows nodes

### ISSUE THREAD

**Issue by davidbgonz** [signalfx/splunk-otel-collector-chart#628]
I'm updating our Splunk otel collectors in a 1.24.6 AKS cluster (on a Windows 2019 node). I'm going from 0.66.1 to 0.67.0 but the agent is having either issues mounting the node logs or retrieving them.

In the logs I am seeing: 
```
2023-01-09T19:23:43.377Z        warn    fileconsumer/file.go:61 no files match the configured include patterns  {"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer", "include": ["C:\\var\\log\\pods\\*\\*\\*.log"], "exclude": ["C:\\var\\log\\pods\\splunk_sitecore-logs-win-splunk-otel-collector*_*\\otel-collector\\*.log"]}
```
I'm not seeing any mounting issues in the kube events

When I try to hop into the container to check the directories I am getting:
```
kubectl -n splunk exec -it sitecore-logs-win-splunk-otel-collector-agent-7464r -- powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved. 


Process is terminated due to StackOverflowException. 
error: error stream protocol error: invalid exit code value "3221225725"
```

For now we can stick to 0.66.1. Is there any new configuration needed for 0.68.0?

This are my values I'm testing with:
```
clusterName: aks-sitecore-dev-eus2
splunkPlatform:
  endpoint: https://***
  token: ***
  index: aks_digital
  insecureSkipVerify: true
  metricsEnabled: false
logsEngine: otel
cloudProvider: azure
distribution: aks
environment: dev
agent:
  controlPlaneMetrics:
    apiserver:
      enabled: false
    controllerManager:
      enabled: false
    coredns:
      enabled: false
    proxy:
      enabled: false
    scheduler:
      enabled: false
  securityContext:
    runAsUser: null
  resources:
    limits:
      cpu: 350m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
priorityClassName: system-cluster-critical
clusterReceiver:
  enabled: false
logsCollection:
  containers:
    useSplunkIncludeAnnotation: true
    multilineConfigs:
      - namespaceName:
          value: sitecore-*
          useRegexp: true
        containerName:
          value: sitecore-*-*
          useRegexp: true
        firstEntryRegex: ^(\s*\d+|\d{4}(-\d{2}){2}|DATE_TIME:|ManagedPoolThread\s#\d|(ERROR|INFO|WARN))\s((\d{2}(:|/)?){3}).*
isWindows: true
image:
  otelcol:
    repository: quay.io/signalfx/splunk-otel-collector-windows
readinessProbe:
  initialDelaySeconds: 60
livenessProbe:
  initialDelaySeconds: 60
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
    effect: NoSchedule
```
