### ISSUE TITLE
Index routing based on marker is not working as expected

### ISSUE THREAD

**Issue by dbhojani** [signalfx/splunk-otel-collector-chart#631]
**logging method :** container > otel > splunk via HEC

Data routing to specific index is configured based on the router:

Helm Chart - Configuration to do marker based index routing :
```
    extraOperators:
      - type: add
        if: body contains '"marker":"GDS"'
        field: resource["com.splunk.index"]
        value: EXPR(resource["k8s.namespace.name"] + "_gds_logs")
      - type: add
        if: body contains '"marker":"GDS_NONPROD"'
        field: resource["com.splunk.index"]
        value: EXPR(resource["k8s.namespace.name"] + "_gds_nonprod_logs")
      - type: add
        if: body contains '"marker":"GDS_LTS"'
        field: resource["com.splunk.index"]
        value: EXPR(resource["k8s.namespace.name"] + "_gds_lts_logs")
      - type: add
        if: body contains '"marker":"BULK"'
        field: resource["com.splunk.index"]
        value: EXPR(resource["k8s.namespace.name"] + "_bulk_logs")
```

Routing is not working as expected for many events. 

**Expected Behavior:**

namespace = test, marker = GDS ---> index=test_gds_logs
namespace = test, marker = GDS_LTS --> index=test_gds_lts
namespace = test && there is no marker OR the marker does not match about condition --> index=test_app_logs

**Current Behavior:**

We are seeing many events with marker=GDS is falling under index=test_app_logs. 
NOTE: Not all events has this issue, many events have correct index name.

One thing we have noticed :
All the GDS messages that ends up in test_app_logs have logtag=P.
[sample_events_incorrect_index.csv](https://github.com/signalfx/splunk-otel-collector-chart/files/10404635/sample_events_incorrect_index.csv)

Attaching sample event as well for review.

Can you please help us with this ? Thank you!
