### ISSUE TITLE
Add ability to enable Logs ONLY but still spawn cluster receiver for API events and Kube Objects

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#632]
Hey team!

In some cases, customers are not looking to us for metrics collection, and only want "log" data. 

It can be confusing to tell them we need to enable metrics so the cluster receiver can be spawned for collection of k8s api events and up coming objects scraping. 

Please update the Splunk configs to allow me to disable metric collection but still collect k8s event and objects data from the cluster receiver

**Comment by omrozowicz-splunk** [comment]
Hey!
It was done as a part of https://github.com/signalfx/splunk-otel-collector-chart/pull/588 
With the newest main version of otel collector such config:

```
clusterName: sck
splunkPlatform:
  endpoint: https://i-0d903f60788be4c68.ec2.splunkit.io:8088/services/collector
  token: XXXX...
  logsEnabled: true
  metricsEnabled: false
  metricsIndex: em_metrics
  index: em_events
  insecureSkipVerify: true
clusterReceiver:
  eventsEnabled: true
```
results with k8s event collection in Splunk.
