### ISSUE TITLE
Index for Kubernetes objects

### ISSUE THREAD

**Issue by Stiuil06** [signalfx/splunk-otel-collector-chart#647]
Which index will be used for k8s objects? 

```
splunk-otel-collector:
  splunkPlatform:
    index: "*_events"
    metricsIndex: "*_metrics"
```

It is possible to specify a separate index (and hec token for this index) for k8s objects (like in SCK)?
