### ISSUE TITLE
Helm chart values for endpoint - explanation

### ISSUE THREAD

**Issue by adamjk-dev** [signalfx/splunk-otel-collector-chart#654]
Recipient..

I am overwriting the endpoint as such in an overrides.yaml for my helm chart installation on OpenShift:

```
splunkPlatform:
  # Required for Splunk Enterprise/Cloud. URL to a Splunk instance to send data
  # to. e.g. "http://X.X.X.X:8088/services/collector". Setting this parameter
  # enables Splunk Platform as a destination.
  endpoint: "https://splunk-hec.example.com"
  # Required for Splunk Enterprise/Cloud (if `endpoint` is specified). Splunk
  # HTTP Event Collector token.
  token: "<<REDACTED>>"
```

However, at install time, it seems that /services/collector is being appended to my endpoint. **Is this expected?** What if I don't want "/services/collector" appended to my endpoint?

Example log:
```
2023-01-31T15:28:09.107Z	info	exporterhelper/queued_retry.go:426	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "splunk_hec/platform_logs", "error": "Post \"https://splunk-hec.example.com/services/collector\": dial tcp <REDACTED>:443: connect: connection refused", "interval": "22.284044367s"}
```

**Comment by atoulme** [comment]
It is expected.

This is set in the collector itself here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/config.go#L120

If you want to change this behavior, please consider opening an issue against the collector contrib project.

**Comment by matthewmodestino** [comment]
Is there a reason not to have it? It is the default HEC event endpoint. Are you serving a custom endpoint?

**Comment by adamjk-dev** [comment]
We just never set that path explicitly before using things like splunk connector for k8s etc. (we just set the FQDN and token).

I believe this is working on my end now:

```
splunkPlatform:
  # Required for Splunk Enterprise/Cloud. URL to a Splunk instance to send data
  # to. e.g. "http://X.X.X.X:8088/services/collector". Setting this parameter
  # enables Splunk Platform as a destination.
  endpoint: "https://splunk-hec.example.com:8088"
  # Required for Splunk Enterprise/Cloud (if `endpoint` is specified). Splunk
  # HTTP Event Collector token.
  token: "<<REDACTED>>"
```

Thanks for the explanation, I think we can close this as a non-issue. I appreciate the quick responses.
