### ISSUE TITLE
Filter Events in k8sobjects

### ISSUE THREAD

**Issue by louise-zhang** [signalfx/splunk-otel-collector-chart#670]
Is it possible to filter namespaces in k8objects using regex?

```
  k8sobjects:
    auth_type: serviceAccount
    objects:
    - mode: watch
      name: events
      namespaces:
      - kube-*
      - openshift-*
      - default
```
