### ISSUE TITLE
Pod Labels are not being captured.

### ISSUE THREAD

**Issue by rmorlenSplunk** [signalfx/splunk-otel-collector-chart#676]
Tried different combinations of yaml settings (in proper yaml format). 

fromLabels:

    - key: app
  
    - key: color
      tag_name: color       
      from: pod

    - key_regex: (.*)
      from: pod
      tag_name: "$$1"

The only label that comes through is app.  (k8s.pod.labels.app).

**Comment by rmorlenSplunk** [comment]
Settings:

  fromLabels:
    - key: app
    
    - key: color
      tag_name: color       
      from: pod

    - key_regex: (.*)
      from: pod
      tag_name: "$$1"

**Comment by matthewmodestino** [comment]
I am working with @rmorlenSplunk on this and have found a few things of note...

1. our component docs do not list the k8sattributes processor [here ](https://github.com/signalfx/splunk-otel-collector/blob/main/docs/components.md)
2. I was able to get this rule to work:

```  
fromLabels:
    - key_regex: (.*)
      from: pod
      tag_name: "$$1"
```

but not this:

```  
fromLabels:
    - key_regex: (.*)
      from: pod
      #tag_name: "$$1"
```
Seems like when I took our the `tag_name` it broke and we didnt see any of the labels with the default naming convention.

**Comment by JosephHobbs** [comment]
We're running into the same issue...  We have a label on the pod that contains an identifier.  If we add that mapping to fromLabels we lose the default 'app' label but don't get the cmdbid label either...

```
extraAttributes:
  fromLabels:
    - key: example.com/cmdbId
      tag_name: cmdbid
      from: pod
```

Any ideas?

**Comment by matthewmodestino** [comment]
what version of the chart are you playing on?

**Comment by JosephHobbs** [comment]
I believe my k8s admins have tried 0.72 and 0.71, both with similar results.

**Comment by matthewmodestino** [comment]
Oh! Is it possible your trying to get annotations, not labels? Your example resembles annotation format. We can pull those too but with this:

https://github.com/signalfx/splunk-otel-collector-chart/blob/34718752a1d602aef5cd066a0d35fd8f30cdb094/helm-charts/splunk-otel-collector/values.yaml#L233


I'll try again for labels and annotations on 0.72.0 when I hit the lab tomorrow!

**Comment by splunkenizer** [comment]
I cannot get this to work as it described in the docs:

`
  fromLabels:
    - key_regex: (.*)
      from: pod
      tag_name: "$$1"
`

This one does work:

`  fromLabels:
    - key_regex: .*
      from: pod
`

**Comment by JosephHobbs** [comment]
> I cannot get this to work as it is described in the docs:
> 
> ```
>   fromLabels:
>     - key_regex: (.*)
>       from: pod
>       tag_name: "$$1"
> ```
> 
> This one does work:
> 
> ```
>   fromLabels:
>     - key_regex: .*
>       from: pod
> ```

Interesting...  I'll have them give this a try and see if it gets them through.

**Comment by matthewmodestino** [comment]
@splunkenizer i have had the exact opposite experience.

Can you please advise what chart version you are on as well...

**Comment by splunkenizer** [comment]
I have tested again now with helm v0.72.0. Actually, I found that the labels are created according to the [docs](https://github.com/signalfx/splunk-otel-collector-chart/blob/34718752a1d602aef5cd066a0d35fd8f30cdb094/helm-charts/splunk-otel-collector/values.yaml#L221). I was just not reading correctly. I was expecting them to be created with the prefix k8s.pod.labels. , which is explicitly mentioned it does not. Just did not look for the explicit fields in the payload. Sorry, my bad.

```
extraAttributes:
  fromLabels:
    - key_regex: (.*)
      from: pod
      tag_name: "$$1"
```

So, to have them created with the prefix, I can either add it like this:

```
extraAttributes:
  fromLabels:
    - key_regex: (.*)
      from: pod
      tag_name: "k8s.pod.labels.$$1"
```
or
```
extraAttributes:
  fromLabels:
    - key_regex: .*
      from: pod
```

Sorry again, for the confusion.
