### ISSUE TITLE
Load Balancing on client side (Splunk Otel Collector)

### ISSUE THREAD

**Issue by naveen-goswami** [signalfx/splunk-otel-collector-chart#683]
As per the documentation; only single Splunk Platform endpoint is possible to configure. This delegates the responsibility to load balance the telemetry ingestion through third party tools such as Nginx. It will be an extra component to manage in the stack. 

```
splunkPlatform:
  # Required for Splunk Enterprise/Cloud. URL to a Splunk instance to send data
  # to. e.g. "http://X.X.X.X:8088/services/collector". Setting this parameter
  # enables Splunk Platform as a destination.
  endpoint: ""
  # Required for Splunk Enterprise/Cloud (if `endpoint` is specified). Splunk
  # HTTP Event Collector token.
  token: ""
```   
Would it be possible to handle load balancing between different endpoints on the client side itself ? Moreover, it'd be great to have some insights into how Otel collector would handle the DNS load balancing.
