### ISSUE TITLE
Otel on Windows nodes - Host field with wrong value

### ISSUE THREAD

**Issue by cesarfr1** [signalfx/splunk-otel-collector-chart#685]
Otel collecting logs on Windows 2022 nodes. 
For the host field, the customer is getting its pod name instead of the actual Windows Hostname.
The same behavior is not observed on Linux-based nodes.

**Comment by atoulme** [comment]
Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor

By default, we use the resourcedetectionprocessor with the system detector to determine the host name.
https://github.com/signalfx/splunk-otel-collector-chart/blob/cc8b2f98f26de7352f0e9d8d433456817c73d9a0/helm-charts/splunk-otel-collector/templates/config/_common.tpl#L84

By default the system detector is set to use the`hostname_sources` ["dns", "os"] and a note in the documentation recommends for Windows hosts to use the `lookup` source instead.
> To produce a FQDN, Windows hosts might have better results using the "lookup" hostname source, which is mentioned below.

Would you please try to customize the chart and add this additional source?

**Comment by omrozowicz-splunk** [comment]
So the additional context here was that the Windows Node was actually on VMware, managed by the openshift cluster. No resource detection settings worked for it. The ultimate workaround we used here was to update `values.yaml` with:

```
agent:
  extraEnvs:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "host.name=$(K8S_NODE_NAME)"
  config:
    processors:
      resourcedetection:
        detectors: ["env"]
```

And this resulted in populating `K8S_NODE_NAME` env variable as the host name.
