### ISSUE TITLE
`extraFileLogs` does not render `storage` parameter by default, may cause duplicate ingestion

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#692]
Hey Team, 

In playing with the `extraFileLogs` option I have found that the `filelog receiver` that is rendered does not add the `storage` parameter to ensure a checkpoint is kept, which will cause duplicate ingestion if the OTel pod is restarted. 

I was able to work around it by adding the parameter manually, but I think we should render it by default:

```
  extraFileLogs:
    filelog/emptydir-mario:
      include:
      - /tmp/emptydir/*/volumes/kubernetes.io~empty-dir/emptydir-mario/catalina*.log
      start_at: beginning
      storage: file_storage
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.index: otel_events
        com.splunk.source: /var/log/emptydir/emptydir-mario
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: mario:tomcat:catalina
      operators:
      - parse_from: attributes["log.file.path"]
        regex: ^\/tmp\/emptydir\/(?P<uid>[^\/]+)\/volumes\/kubernetes\.io\~empty\-dir\/(?P<volume_name>[^\/]+)\/.+$
        type: regex_parser
      - from: attributes.uid
        to: resource["k8s.pod.uid"]
        type: move
      - from: attributes.volume_name
        to: resource["k8s.volume.name"]
        type: move
```
