### ISSUE TITLE
How to get metric from Persistent Volume Claim?

### ISSUE THREAD

**Issue by Dannhausen** [signalfx/splunk-otel-collector-chart#702]
Hi,
we have a setup with different pods using PVC´s and we need to monitor them (the PVC´s).
I couldnt find any definition, how to do that correctly with the otel collector.

My actual try:
```
clusterReceiver:
  config:
    receivers:
      kubeletstats:
         collection_interval: 60s
         auth_type: "serviceAccount"
         endpoint: "10.122.225.70:10250"
         insecure_skip_verify: true
         metric_groups:
           - node
           - pod
           - container
           - volume
         extra_metadata_labels:
           - k8s.volume.type
           - container.id
         k8s_api_config:
           auth_type: serviceAccount
      hostmetrics:
        collection_interval: 60s
        auth_type: "serviceAccount"
        endpoint: "10.122.225.70:10250"
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
          - volume
        extra_metadata_labels:
          - k8s.volume.type
          - container.id
        k8s_api_config:
          auth_type: serviceAccount
    processors:
      batch:
    exporters:
      logging:
    service:
      pipelines:
        metrics:
          receivers: [kubeletstats,hostmetrics]
          processors: [batch]
          exporters: [logging]
```
If i search in Splunk with | mcatalog values(metric_name) WHERE index=mymetricindex, i even dont get a k8s.volume.type. Not shure btw this would be the right metric index i want to be honest.

Any hints?
