### ISSUE TITLE
Wrong timestamp in Splunk with otel instead of fluentd

### ISSUE THREAD

**Issue by dxniel7402** [signalfx/splunk-otel-collector-chart#714]
Hello all,

I just want to migrate from splunk-connect-for-kubernetes to here. I noticed that I have the following paragraph for fluentd:
```yaml
fluentd:
  configs:
    logs:
      gwv6:
        from:
          pod: gwv6-*
            container: gwv6
          timestampExtraction:
            format: "%Y%m%dT%H%M%S.%3N%z"
          sourcetype: syslog_gwv6
```
The `timestampExtraction` process is important to me here, without it, the timestamps are displayed incorrectly in Splunk.

Unfortunately, I can't implement this with otel, according to your example, where `timestampExtraction` is mentioned: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md#extra-files-from-host

So the question is, how can I translate this here?

**Comment by dxniel7402** [comment]
I have now been able to solve our problem with my colleagues. The following is now under `logsCollection.containers.extraOperators`:

```yaml
    - id: gwv6_custom-timestamp
      type: regex_parser
      if: resource["k8s.container.name"] == "gwv6"
      parse_from: attributes.log
      regex: '^(?P<custom_timestamp>\S+)'
      timestamp:
        parse_from: attributes.custom_timestamp
        layout_type: strptime
        layout: "%Y%m%dT%H%M%S.%LZ"
```

Wasn't part of the issue, but still worth mentioning: I wanted to enable multiline logs, [but that doesn't seem to work](https://github.com/signalfx/splunk-otel-collector-chart/issues/633) if you have already enabled `extraOperators`. Therefore, this has become the solution for me, also under `extraOperators`:

```yaml
    - id: gwv6_multiline
      type: recombine
      combine_field: attributes.log
      is_first_entry: (attributes.log) matches "^(\\d{4})(\\d{2})(\\d{2})T(\\d{2})(\\d{2})(\\d{2})\\.\\d{3}Z\\s+\\[[^\\]]+\\]"
      source_identifier: resource["com.splunk.source"]
```

The next important thing for me was that I can also change the sourcetype and the index accordingly, as specifically from this container is needed. Here it gets more complicated, because you have to remove and add here:

```yaml
    - id: gwv6_remove-standard-sourcetype
      type: remove
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.sourcetype"]
    - id: gwv6_add-custom-sourcetype
      type: add
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.sourcetype"]
      value: syslog_gwv6
    - id: gwv6_remove-standard-index
      type: remove
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.index"]
    - id: gwv6_add-custom-index
      type: add
      if: resource["k8s.container.name"] == "gwv6"
      field: resource["com.splunk.index"]
      value: gwv6_index
```

If someone also encounters such problems, I hope to have helped in detail :-)
