### ISSUE TITLE
Question on documentation for migrating from SCK

### ISSUE THREAD

**Issue by cheevs** [signalfx/splunk-otel-collector-chart#754]
### Describe the issue you're reporting

On the documentation for migration from SCK. 
https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md#extracted-fields-for-logs

``` yaml
splunkPlatform:
  fieldNameConvention:
    # Boolean for renaming pod metadata fields to match to Splunk Connect for Kubernetes helm chart.
    renameFieldsSck: true
    # Boolean for keeping Otel convention fields after renaming it
    keepOtelConvention: false
```

Are there any expected forward compatibility issues in the future? Are there any downsides to keeping the old naming convention? Will there be any impact for future upgrades or deprecations?
