### ISSUE TITLE
Make excluded istio attributes easily configurable

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#769]
Follow-up for the discussion in https://github.com/signalfx/splunk-otel-collector-chart/pull/765#discussion_r1183056540

Find a way to transition from

```yaml
autodetect:
  istio: bool
```

to 

```yaml
autodetect:
  istio:
    enabled: true
    # Explain why we remove these default set of attributes
    excludeAttributes:
    - attr1
    - attr2
```

in backward compatible way
