### ISSUE TITLE
Pods annotated with splunk.com/index annotation send metrics to an event index

### ISSUE THREAD

**Issue by dmitrykruglov** [signalfx/splunk-otel-collector-chart#784]
## Description

Hi team, we are currently using the Splunk Otel Collector to send both logs and metrics to Splunk.
While testing the index routing feature using `splunk.com/index` annotation, we found out that although the logs are indeed being sent to the specified index, container metrics are being sent to the same event index as well. This seems like a bug, because the event index is not well suited for the metrics data. And it's not ideal for our use case, because our intention is to only reroute logs, not metrics. 

## Steps to Reproduce

1. Configure splunk-otel-collector to collect both metrics and logs, to a metrics and events indexes, respectively. 
2. Annotate a pod with "splunk.com/index" annotation.
3. Observe that not only logs but also metrics are forwarded to the specified index.

## Expected Result

Only logs are being sent to the specified events index. 

## Actual Result

Both logs and container metrics are being sent to the specified events index. 

### Chart version

v0.72.0

## Environment
Cloud: EKS
k8s version: 1.24
OS: Amazon Linux

**Comment by dmitrykruglov** [comment]
Hi @omrozowicz-splunk,

Thank you for looking into this. Yes, you are correct, we are seeing metrics events appearing as log events in the event index. Specifically, we are receiving metrics like `container.memory.working_set`, `k8s.pod.network.errors`, `k8s.pod.memory.working_set`, `k8s.pod.memory.rss`, etc. I think these are kubelet metrics, but not entirely sure.

Additionally, our pod is annotated with the `prometheus.io/scrape` annotation, and we've noticed that our custom Prometheus metrics are also ending up in the event index.

Here are the annotations we've set on our test pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: mytest
  namespace: mynamespace
  annotations:
    "splunk.com/include": "true"
    splunk.com/index: mysplunkindex
    prometheus.io/path: /prom-metrics
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
```

Also, forgot to mention, that we're using the HEC exporter to forward these events to Splunk (not Splunk Observability Cloud).

**Comment by omrozowicz-splunk** [comment]
Hey, thanks for confirmation!
Can you share your agent configmap as well? It will help me to reproduce.
I think this might be something specific to your configuration (after adding other annotations it is still working fine for me).

**Comment by dmitrykruglov** [comment]
Sure, here's the agent configmap we are currently using. It has some additional functionality to filter logs based on log level, and also add k8s annotations and labels as dimensions to metrics, but otherwise should be pretty similar to the stock helm chart's configuration. 
 
```
exporters:
  splunk_hec/platform_logs:
    disable_compression: false
    endpoint: https://hec.example.com:8088/services/collector
    index: events-index
    max_connections: 200
    profiling_data_enabled: false
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 100
    source: kubernetes
    splunk_app_name: splunk-otel-collector
    splunk_app_version: 0.72.0
    timeout: 30s
    tls:
      insecure_skip_verify: false
    token: ${SPLUNK_PLATFORM_HEC_TOKEN}
  splunk_hec/platform_metrics:
    disable_compression: false
    endpoint: https://hec.example.com:8088/services/collector
    index: metrics-index
    max_connections: 200
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 100
    source: kubernetes
    splunk_app_name: splunk-otel-collector
    splunk_app_version: 0.72.0
    timeout: 30s
    tls:
      insecure_skip_verify: false
    token: ${SPLUNK_PLATFORM_HEC_TOKEN}
extensions:
  file_storage:
    directory: /var/addon/splunk/otel_pos
  health_check: null
  k8s_observer:
    auth_type: serviceAccount
    node: ${K8S_NODE_NAME}
  memory_ballast:
    size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
  zpages: null
processors:
  batch: null
  filter/log_level:
    logs:
      exclude:
        match_type: regexp
        resource_attributes:
        - key: k8s.pod.annotations.example.com/trace
          value: ^([^t].*|[t][^r].*|[t][r]([^u].*|u)|tru[^e]|true.+)$
        severity_texts:
        - ^$
        - TRACE[2-4]?
        - DEBUG[2-4]?
  filter/logs:
    logs:
      include:
        match_type: strict
        resource_attributes:
        - key: splunk.com/include
          value: "true"
  k8sattributes:
    extract:
      annotations:
      - from: pod
        key: splunk.com/sourcetype
      - from: namespace
        key: splunk.com/include
        tag_name: splunk.com/include
      - from: pod
        key: splunk.com/include
        tag_name: splunk.com/include
      - from: namespace
        key: splunk.com/index
        tag_name: com.splunk.index
      - from: pod
        key: splunk.com/index
        tag_name: com.splunk.index
      - key_regex: example.com.*
      labels:
      - key_regex: app.kubernetes.io.*
      - key_regex: example.com.*
      metadata:
      - k8s.namespace.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - container.id
      - container.image.name
      - container.image.tag
    filter:
      node_from_env_var: K8S_NODE_NAME
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: ip
    - sources:
      - from: connection
    - sources:
      - from: resource_attribute
        name: host.name
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resource:
    attributes:
    - action: insert
      key: k8s.node.name
      value: ${K8S_NODE_NAME}
    - action: upsert
      key: k8s.cluster.name
      value: test
  resource/add_agent_k8s:
    attributes:
    - action: insert
      key: k8s.pod.name
      value: ${K8S_POD_NAME}
    - action: insert
      key: k8s.pod.uid
      value: ${K8S_POD_UID}
    - action: insert
      key: k8s.namespace.name
      value: ${K8S_NAMESPACE}
  resource/logs:
    attributes:
    - action: upsert
      from_attribute: k8s.pod.annotations.splunk.com/sourcetype
      key: com.splunk.sourcetype
    - action: delete
      key: k8s.pod.annotations.splunk.com/sourcetype
    - action: delete
      key: splunk.com/include
  resource/logs_trace:
    attributes:
    - action: insert
      key: k8s.pod.annotations.example.com/trace
      value: "false"
  resourcedetection:
    detectors:
    - env
    - eks
    - ec2
    - system
    override: true
    timeout: 10s
receivers:
  filelog:
    encoding: utf-8
    exclude:
    - /var/log/pods/monitoring_splunk-otel-collector*_*/otel-collector/*.log
    - /var/log/pods/kube-system_aws-cluster-autoscaler*/*/*.log
    - /var/log/pods/kube-system_kube-proxy*/*/*.log
    fingerprint_size: 1kb
    force_flush_period: "0"
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    max_concurrent_files: 1024
    max_log_size: 1MiB
    operators:
    - id: get-format
      routes:
      - expr: body matches "^\\{"
        output: parser-docker
      - expr: body matches "^[^ Z]+ "
        output: parser-crio
      - expr: body matches "^[^ Z]+Z"
        output: parser-containerd
      type: router
    - id: parser-crio
      regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: "2006-01-02T15:04:05.999999999-07:00"
        layout_type: gotime
        parse_from: attributes.time
      type: regex_parser
    - combine_field: attributes.log
      combine_with: ""
      id: crio-recombine
      is_last_entry: attributes.logtag == 'F'
      output: handle_empty_log
      source_identifier: attributes["log.file.path"]
      type: recombine
    - id: parser-containerd
      regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: regex_parser
    - combine_field: attributes.log
      combine_with: ""
      id: containerd-recombine
      is_last_entry: attributes.logtag == 'F'
      output: handle_empty_log
      source_identifier: attributes["log.file.path"]
      type: recombine
    - id: parser-docker
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: json_parser
    - combine_field: attributes.log
      combine_with: ""
      id: docker-recombine
      is_last_entry: attributes.log endsWith "\n"
      output: handle_empty_log
      source_identifier: attributes["log.file.path"]
      type: recombine
    - field: attributes.log
      id: handle_empty_log
      if: attributes.log == nil
      type: add
      value: ""
    - parse_from: attributes["log.file.path"]
      regex: ^\/var\/log\/pods\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[^\/]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
      type: regex_parser
    - from: attributes.uid
      to: resource["k8s.pod.uid"]
      type: move
    - from: attributes.restart_count
      to: resource["k8s.container.restart_count"]
      type: move
    - from: attributes.container_name
      to: resource["k8s.container.name"]
      type: move
    - from: attributes.namespace
      to: resource["k8s.namespace.name"]
      type: move
    - from: attributes.pod_name
      to: resource["k8s.pod.name"]
      type: move
    - field: resource["com.splunk.sourcetype"]
      type: add
      value: EXPR("kube:container:"+resource["k8s.container.name"])
    - from: attributes.stream
      to: attributes["log.iostream"]
      type: move
    - from: attributes["log.file.path"]
      to: resource["com.splunk.source"]
      type: move
    - default: clean-up-log-record
      id: get-log-format
      routes:
      - expr: attributes.log matches "^\\s*{.*}\\s*$"
        output: parse-log-level-json
      - expr: attributes.log matches "\\s*(?P<log_level>(TRACE|DEBUG|INFO|WARN|ERROR|FATAL)[2-4]?)[:\\s]\\s*\\S+"
        output: parse-log-level-nonjson
      type: router
    - id: parse-log-level-json
      if: attributes.log matches "^\\s*{.*\"level\"\\s*:.*}\\s*$"
      output: clean-up-log-record
      parse_from: attributes.log
      parse_to: body.tempLog
      severity:
        parse_from: body.tempLog["level"]
      type: json_parser
    - id: parse-log-level-nonjson
      output: clean-up-log-record
      parse_from: attributes.log
      regex: \s*(?P<level>(TRACE|DEBUG|INFO|WARN|ERROR|FATAL)[2-4]?)[:\s]\s*\S+
      severity:
        parse_from: attributes.level
      type: regex_parser
    - from: attributes.log
      id: clean-up-log-record
      to: body
      type: move
    poll_interval: 200ms
    start_at: beginning
    storage: file_storage
  fluentforward:
    endpoint: 0.0.0.0:8006
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: null
      disk: null
      filesystem: null
      load: null
      memory: null
      network: null
      paging: null
      processes: null
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 60s
    endpoint: ${K8S_NODE_IP}:10250
    extra_metadata_labels:
    - container.id
    metric_groups:
    - container
    - pod
    - node
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/agent:
    config:
      scrape_configs:
      - job_name: otel-agent
        scrape_interval: 60s
        static_configs:
        - targets:
          - ${K8S_POD_IP}:8889
  receiver_creator:
    receivers:
      prometheus_simple:
        config:
          collection_interval: 60s
          endpoint: '`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"]
            : 9090`'
          metrics_path: '`"prometheus.io/path" in annotations ? annotations["prometheus.io/path"]
            : "/metrics"`'
        rule: type == "pod" && annotations["prometheus.io/scrape"] == "true"
    watch_observers:
    - k8s_observer
  signalfx:
    endpoint: 0.0.0.0:9943
service:
  extensions:
  - file_storage
  - health_check
  - k8s_observer
  - memory_ballast
  - zpages
  pipelines:
    logs:
      exporters:
      - splunk_hec/platform_logs
      processors:
      - memory_limiter
      - k8sattributes
      - batch
      - filter/logs
      - resource/logs_trace
      - filter/log_level
      - resource/logs
      - resourcedetection
      - resource
      receivers:
      - filelog
      - fluentforward
      - otlp
    metrics:
      exporters:
      - splunk_hec/platform_metrics
      processors:
      - memory_limiter
      - k8sattributes
      - batch
      - resourcedetection
      - resource
      receivers:
      - hostmetrics
      - kubeletstats
      - otlp
      - receiver_creator
      - signalfx
    metrics/agent:
      exporters:
      - splunk_hec/platform_metrics
      processors:
      - memory_limiter
      - batch
      - resource/add_agent_k8s
      - resourcedetection
      - resource
      receivers:
      - prometheus/agent
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8889
```

**Comment by omrozowicz-splunk** [comment]
I think what is causing this problem for you is `k8sattributes` processor under metrics pipeline, and especially this part:

```
      - from: namespace
        key: splunk.com/index
        tag_name: com.splunk.index
      - from: pod
        key: splunk.com/index
        tag_name: com.splunk.index
```

I didn't go into the details of your config, but I created another k8sattributes without index part:

```
    processors:
      k8sattributes/metrics:
        extract:
          annotations:
          - from: pod
            key: splunk.com/sourcetype
          - from: namespace
            key: splunk.com/include
            tag_name: splunk.com/include
          - from: pod
            key: splunk.com/include
            tag_name: splunk.com/include
          - key_regex: example.com.*
          labels:
          - key_regex: app.kubernetes.io.*
          - key_regex: example.com.*
          metadata:
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - container.id
          - container.image.name
          - container.image.tag
        filter:
          node_from_env_var: K8S_NODE_NAME
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: ip
        - sources:
          - from: connection
        - sources:
          - from: resource_attribute
            name: host.name
```
And replaced in the metrics pipeline:
```
      pipelines:
        metrics:
          exporters:
          - splunk_hec/platform_metrics
          processors:
          - memory_limiter
          - batch
          - k8sattributes/metrics
          - resourcedetection
          - resource
          receivers:
          - hostmetrics
          - kubeletstats
          - otlp
          - receiver_creator
          - signalfx
```
And it fixed issue for me. Please try it out.
