### ISSUE TITLE
otel and fluentforward receivers are always enabled

### ISSUE THREAD

**Issue by joshmue** [signalfx/splunk-otel-collector-chart#808]
### Describe the issue you're reporting

[`values.yaml`](https://github.com/signalfx/splunk-otel-collector-chart/blob/6646f31acdcd43af680de70dcf514e26afd7ceab/helm-charts/splunk-otel-collector/values.yaml#L309) indicates that one should `Make sure that only necessary ports are exposed`:

```yaml
...
  # The ports to be exposed by the agent to the host.
  # Make sure that only necessary ports are exposed, <hostIP, hostPort, protocol> combination must
  # be unique across all the nodes in k8s cluster. Any port can be disabled,
  # For example to disable zipkin ports set `agent.ports.zipkin: null`.
  ports:
    otlp:
      containerPort: 4317
      hostPort: 4317
      protocol: TCP
      enabled_for: [traces, metrics, logs, profiling]
...
```

As far as I can tell, disabling ports by setting `enabled_for` to `[]` indeed removes the `port` definition in the Pod specs. But the otel and fluentforward receivers are pretty much hardcoded in the [actual collector configuration](https://github.com/signalfx/splunk-otel-collector-chart/blob/6646f31acdcd43af680de70dcf514e26afd7ceab/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L26), opening these receivers to the whole network, as `hostNetwork` is set to `true` (on non-windows).

Making `hostNetwork` opt-in (See #133) would already improve the situation, as usual `NetworkPolicies` can be applied, then. Going further, it would be good to be actually able to disable unused ports.

But as-is, either I missed something or there is indeed no option to disable otel receivers (and fluentforward if `logsEnabled` is `true`) when they are not needed.
