### ISSUE TITLE
Reading index resource attribute doesn't work when gateway mode is on

### ISSUE THREAD

**Issue by omrozowicz-splunk** [signalfx/splunk-otel-collector-chart#848]
## Description

User wanted to use this transform:
```
      transform/index_stderr:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - set(attributes["index3"],Concat([resource.attributes["my_index"],attributes["stderr_index"]],""))
```
To concatenate the name of index with a suffix. The problem was, that it didn't work (instead of index it was adding the `{}`).
What helped was disabling the `gateway` mode.

## Steps to Reproduce
Add this transform to `values.yaml`:
```
      transform/index_stderr:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              #- set(attributes["a_attribute_index"],resource.attributes["splunk.index"])
              - set(attributes["index3"],Concat([resource.attributes["my_index"],"_err"],""))
```
and add transform to processors.
Enable `gateway`

## Expected Result
Visible `index3` attribute with the correct index and "_err" suffix.

## Actual Result
"{}_err" as an `index3` attribute

### Chart version

0.80.0

## Environment
EC2

**Comment by jvoravong** [comment]
@omrozowicz-splunk for clarification, did you add the ` transform/index_stderr` processor to the collector agent configuration or collector gateway configuration?

**Comment by omrozowicz-splunk** [comment]
> @omrozowicz-splunk for clarification, did you add the ` transform/index_stderr` processor to the collector agent configuration or collector gateway configuration?

Hey, yes, forgot to mention it in the issue, but the pipelines looked like:

```
    service:
      pipelines:
        logs:
          exporters:
          - splunk_hec/platform_logs
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection
          - resource
          - resource/logs
          - transform/index_stderr
...
```

I'm sure it is about a gateway, as switching it off immediately fixed the issue.

**Comment by omrozowicz-splunk** [comment]
Okay, I revisited this issue and the case here was that when agent + gateway are enabled, the `transform/index_stderr` config should be put under `gateway.config` instead of `agent.config`. On the agent level we should still adjust attributes:
```
    extraOperators:
      - id: set_stderr_to_new_index
        type: add
        field: attributes.stderr_index
        value: "_stderr"
        if: attributes["log.iostream"] == "stderr"
      - id: set_stderr_to_blank
        type: add
        field: attributes.stderr_index
        value: "_err"
        if: attributes["log.iostream"] == "stdout"
      - from: attributes.stderr_index
        to: attributes["stderr_index"]
        type: move
```
But we should transform at `gateway` level to correctly route events to the right index.
