### ISSUE TITLE
unable to map health_check extension to localhost

### ISSUE THREAD

**Issue by zencircle** [signalfx/splunk-otel-collector-chart#851]
## Description
Health check warning in the logs
## Steps to Reproduce
```
helm upgrade --install myotel  \
--namespace splunk-monitoring \
--create-namespace \
-f values.yaml \
splunk-otel-collector-chart/splunk-otel-collector
```
## Expected Result
No warnings
## Actual Result
Warnings in the pod logs 

### Chart version

0.80.0

## Environment
Cloud: EKS
k8s version: 1.21
OS: Amazon Linux

### Chart configuration

```yaml
clusterName: eksexample1
splunkPlatform:
  token: XXX
  endpoint: https://example.com:8088/services/collector
  index: kubernetes
  insecureSkipVerify: true
logsEngine: otel
tolerations:
  - operator: Exists
agent:
  config:
    receivers:
      fluentforward:
        endpoint: localhost:8006
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
    service:
      telemetry:
        metrics:
          address: localhost:8889
      extensions:
        health_check:
          endpoint: localhost:13133
```

### Log output

```shell
023-07-17T20:53:21.539Z	info	healthcheckextension@v0.80.0/healthcheckextension.go:34	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"0.0.0.0:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2023-07-17T20:53:21.540Z	warn	internal@v0.80.0/warning.go:40	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks	{"kind": "extension", "name": "health_check", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
```

### Additional context

CHART                       	APP VERSION
myotel	splunk-monitoring	1       	2023-07-18 11:24:28.36463 -0400 EDT	deployed	splunk-otel-collector-0.80.0	0.80.0  

Note: otel is working as expected and is sending data to the collecting. I would liket run the health check on localhost and remove the warning

**Comment by VihasMakwana** [comment]
I would like to examine the relay.yaml. 
you can do 
`kubectl exec -it PODNAME -- cat /conf/relay.yaml` and attach the output.

Apart from that, please try out below config
```
clusterName: eksexample1
splunkPlatform:
  token: XXX
  endpoint: https://example.com:8088/services/collector
  index: kubernetes
  insecureSkipVerify: true
logsEngine: otel
tolerations:
  - operator: Exists
agent:
  config:
    extensions:
      health_check:
          endpoint: localhost:13133
    receivers:
      fluentforward:
        endpoint: localhost:8006
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
    service:
      telemetry:
        metrics:
          address: localhost:8889
```
