### ISSUE TITLE
Pod labels for splunk source and sourcetype overwrite not being respected

### ISSUE THREAD

**Issue by saiharshitachava** [signalfx/splunk-otel-collector-chart#862]
### What happened?

We installed the latest version of 0.81.0 chart and I see the custom pod labels to overwrite splunk source and scourctype isnt working but the index is working

I know the docs say we need to switch to annotations

But is there a back door (may be not via helm) to do this source and sourcetype overwrite  from custom pod labels?

### Chart version

0.81.0

### Environment information

EKS 1.25

**Comment by rmfitzpatrick** [comment]
Can you please provide any relevant values configuration and (redacted) examples of the observed change in behavior?

**Comment by saiharshitachava** [comment]
@rmfitzpatrick any luck here

**Comment by omrozowicz-splunk** [comment]
I took a look at it and looks like `com.splunk.source` and `com.splunk.sourcetype` works only if we remove it first from filelog `extraOperators`. My config:

```
logsCollection:
  containers:
    extraOperators:
      - type: remove
        field: resource["com.splunk.source"]
      - type: remove
        field: resource["com.splunk.sourcetype"]
extraAttributes:
  fromLabels:
    - key: splunk.abc.com/splunk-index
      tag_name: com.splunk.index
      from: pod
    - key: splunk.abc.com/splunk-source
      tag_name: com.splunk.source
      from: pod
    - key: splunk.abc.com/splunk-sourcetype
      tag_name: com.splunk.sourcetype
      from: pod
```

Note that `remove` requires an additional `if` statement to be applicable only to pods you're interested in, otherwise it will remove sourcetypes and source from all the data.

I'll try to see if there's a better way and/or why it works differently for index, but this is the best I have so far.

**Comment by saiharshitachava** [comment]
@omrozowicz-splunk 
Is there an example around this condition ?

**Comment by omrozowicz-splunk** [comment]
> @omrozowicz-splunk Is there an example around this condition ?

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/remove.md
Here you can refer to `if` field. An example of such a case would be for example: `if: 'resource["k8s.pod.name"] contains "mongo"'`

**Comment by saiharshitachava** [comment]
Thanks @omrozowicz-splunk 

One more quick question
I extracted these custom labels from pod how do I access the values of that label key?

Lets say this is extracted splunk.abc.com/splunk-sourcetype how do I refer to the value of this under operators section?

**Comment by saiharshitachava** [comment]
im thinking to remove source if custom labels field is not nil and assign the value in labels key to source

**Comment by saiharshitachava** [comment]
Anything on this? If we atleast know which version doesnt have this bug I can switch to that for now

**Comment by omrozowicz-splunk** [comment]
I think to chceck if we even have custom labels it's better to do soemthing like `"k8s.pod.labels.splunk.abc.com/sourcetype" in attributes` or "k8s.pod.labels.splunk.abc.com/sourcetype" in resource`, that `if` statement language follows this specification: https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md

Can you tell me which version is the last that worked for you?

**Comment by saiharshitachava** [comment]
0.43.2 is the last version of helm chart thats worked for us

**Comment by omrozowicz-splunk** [comment]
@saiharshitachava 
Ok, actually I have a solution that is much easier to implement.

Can you try:

```
extraAttributes:
  fromLabels:
    - key: splunk.abc.com/splunk-index
      tag_name: com.splunk.index
      from: pod
    - key: splunk.abc.com/splunk-source
      from: pod
    - key: splunk.abc.com/splunk-sourcetype
      from: pod
agent:
  config:
    processors:
      resource/logs:
        attributes:
        - action: upsert
          from_attribute: k8s.pod.labels.splunk.abc.com/splunk-sourcetype
          key: com.splunk.sourcetype
        - action: upsert
          from_attribute: k8s.pod.labels.splunk.abc.com/splunk-source
          key: com.splunk.source
        - action: delete
          key: k8s.pod.annotations.splunk.com/sourcetype
        - action: delete
          key: k8s.pod.labels.splunk.abc.com/splunk-sourcetype
        - action: delete
          key: k8s.pod.labels.splunk.abc.com/splunk-source
        - action: delete
          key: splunk.com/exclude
```

Adding these `resource/logs` upserts worked for me
