### ISSUE TITLE
Fresh install fails since chart v0.77.0

### ISSUE THREAD

**Issue by sleterrier** [signalfx/splunk-otel-collector-chart#868]
## Description
Initial `helm install` fails since chart v0.77.0.

## Steps to Reproduce
```
helm install splunk-collector splunk-otel-collector-chart/splunk-otel-collector -f values.yaml --version 0.77.0
```

## Expected Result
`helm install` should succeed.

## Actual Result
Fails secret validation due to missing serviceAccount.

### Chart version

0.77.0+

## Environment
Cloud: EKS + vanilla Kubernetes
k8s version: 1.25

### Chart configuration

```yaml
agent:
  controlPlaneMetrics:
    apiserver:
      enabled: false
    controllerManager:
      enabled: false
    coredns:
      enabled: false
    etcd:
      enabled: false
    proxy:
      enabled: false
    scheduler:
      enabled: false
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi
certmanager:
  enabled: false
  installCRDs: false
clusterName: cluster-name
clusterReceiver:
  enabled: false
environment: dev
extraAttributes:
  fromAnnotations:
  - from: namespace
    key_regex: (example.net/.*)
    tag_name: $$1
  - from: pod
    key_regex: (example.net/.*)
    tag_name: $$1
  fromLabels:
  - from: namespace
    key_regex: (example.net/.*)
    tag_name: $$1
  - from: pod
    key_regex: (example.net/.*)
    tag_name: $$1
logsCollection:
  containers:
    enabled: true
    useSplunkIncludeAnnotation: true
logsEngine: otel
secret:
  create: false
  name: splunk-otel-collector
serviceAccount:
  create: true
  name: splunk-collector
splunkPlatform:
  endpoint: https://http-inputs-obfuscated.splunkcloud.com/services/collector
  index: kubernetes_logs
  logsEnabled: true
  metricsEnabled: false
  tracesEnabled: false
```

### Log output

```shell
Error: INSTALLATION FAILED: failed pre-install: warning: Hook pre-install splunk-otel-collector/templates/secret-splunk-validation-hook.yaml failed: pods "splunk-collector-splunk-otel-collector-validate-secret" is forbidden: error looking up service account splunk/splunk-collector: serviceaccount "splunk-collector" not found
```

### Additional context

https://github.com/signalfx/splunk-otel-collector-chart/pull/781 is likely the culprit.
