### ISSUE TITLE
EXPR with runtime env not added to log entry

### ISSUE THREAD

**Issue by philipsabri** [signalfx/splunk-otel-collector-chart#881]
## Description
When upgrading to 0.82.0 we noticed that our ``'EXPR(env("K8S_NODE_NAME"))'`` stopped working, we are using it as it is showed in the helm values example https://github.com/signalfx/splunk-otel-collector-chart/blob/919e6cca5f3939eff64b6d6ec922b0088f1b67ab/helm-charts/splunk-otel-collector/values.yaml#L613

It works on previous version, tested between `0.76.0` - `0.81.0`

## Steps to Reproduce
```
splunkPlatform:
  index: main
  insecureSkipVerify: true
  endpoint: https://url.com/services/collector/event?auto_extract_timestamp=true
secret:
  name: hec-token
  create: false
  validateSecret: false
clusterReceiver:
  eventsEnabled: false
  enabled: false
logsEngine: otel
logsCollection:
  extraFileLogs:
    filelog/test:
      include: [/log.txt]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:test
clusterName: docker-desktop
```
Exec into the otel pod and run ``echo "test" >> /log.txt`` a few times to trigger the error

## Expected Result
Should work as in previous versions

## Actual Result
```
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.82.0/fileconsumer/reader.go:111
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.82.0/fileconsumer/file.go:163
2023-08-09T09:35:39.898Z        error   fileconsumer/reader.go:111      process: %w     {"kind": "receiver", "name": "filelog/audit-log-openshift-apiserver", "data_type": "logs", "component": "fileconsumer", "path": "/var/log/openshift-apiserver/audit.log", "error": "create entry: add resource keys to entry: render embedded expression: reflect: call of reflect.Value.Call on map Value (1:1)\n | env(\"K8S_NODE_NAME\")\n | ^"}
```

### Chart version

0.82.0

## Environment
Docker-desktop Kubernetes v1.25.4
Openshift 4.12.5 with kubernetes v1.25.4+a34b9e9
