### ISSUE TITLE
Multiline regex not populating in agent configmap

### ISSUE THREAD

**Issue by gusdebbaja** [signalfx/splunk-otel-collector-chart#911]
## Description
When using logsCollection.continers.mulitlineConfigs , configuring firstEntryRegex should be mapped to the recombine opreator in the log operator when the Otel Collector is deployed.

Currently (tested in version 0.78.0 and 0.83.0), when configuring this Helm value, the value `expr` in the attribute `firstEntryRegex` doesn't get populated.
```
  logsCollection:
    containers:
      multilineConfigs:
        - namespaceName:
            value: my-multiline-namespace.*
            useRegexp: true
            firstEntryRegex: ^\\d{4}-[0-1]\\d-[0-3]\\d\\s[0-2]\\d:[0-5]\\d:[0-5]\\d

```
## Steps to Reproduce
Deploy current config for Chart version 0.83.0:
```
clusterName: "my_ocp_cluster"
splunkPlatform:
  endpoint: "http://X.X.X.X:8088/services/collector"
  token: "my_token"

  index: "main"
  logsCollection:
    containers:
      multilineConfigs:
        - namespaceName:
            value: my-multiline-namespace.*
            useRegexp: true
            firstEntryRegex: ^\\d{4}-[0-1]\\d-[0-3]\\d\\s[0-2]\\d:[0-5]\\d:[0-5]\\d

```
## Expected Result
The rendered config map should have this operator in the filelog receiver: 
```
    - combine_field: attributes.log
      id: my-multiline-namespace.*
      is_first_entry: '(attributes.log) matches "^\\d{4}-[0-1]\\d-[0-3]\\d\\s[0-2]\\d:[0-5]\\d:[0-5]\\d"'
      output: clean-up-log-record
      source_identifier: resource["com.splunk.source"]
      type: recombine
```

## Actual Result
But actually this gets rendered: 
```
      - combine_field: attributes.log
        id: my-multiline-namespace.*
        is_first_entry: '(attributes.log) matches '
        max_log_size: 1048576
        output: clean-up-log-record
        source_identifier: resource["com.splunk.source"]
        type: recombine
```

### Chart version

0.78.0, 0.83.0

## Environment
Openshift
