### ISSUE TITLE
Exclude events from k8sObjects inside clusterReceiver

### ISSUE THREAD

**Issue by ProboticsX** [signalfx/splunk-otel-collector-chart#922]
### Describe the issue you're reporting

Hi,

I needed to know if there's any way to exclude a certain type of events to be sent to Splunk? 
For eg: I want to exclude logs with k8s.event.reason=PolicyViolation or k8s.event.reason=PolicyApplied to be sent to Splunk, so how should I modify the values.yaml file?

This is how the values file currently looks like:

```
clusterReceiver:
  eventsEnabled: true
  k8sObjects:
    - name: events
      mode: watch
      group: events.k8s.io
```
