### ISSUE TITLE
Installing 0.86.0 chart fails due to chart validation regarding instrumentation.spec.go

### ISSUE THREAD

**Issue by mohaldu** [signalfx/splunk-otel-collector-chart#964]
Hi,

I'm installing 0.86.0 of this chart with these values below, but this fails with the following err:

**error:**
```
error validating data: ValidationError(Instrumentation.spec): unknown field "go" in io.opentelemetry.v1alpha1.Instrumentation.spec
```

Note, I can see the chart installing CRDs versioned v0.12.0 for ``opentelemetrycollectors.opentelemetry.io`` and ``instrumentations.opentelemetry.io``

**values:** 

```
     values: |
        clusterName: xx
        environment: xx
        agent:
          config:
            processors:
              resource/delete:
                attributes:
                  - key: "telemetry.auto.version"
                    action: delete
                  - key: "net.protocol.version"
                    action: delete
                  - key: "telemetry.sdk.version"
                    action: delete
                  - key: "telemetry.sdk.language"
                    action: delete
                  - key: "telemetry.sdk.name"
                    action: delete
                  - key: "process.executable.path"
                    action: delete
                  - key: "process.command_args"
                    action: delete
                  - key: "process.runtime.name"
                    action: delete
                  - key: "process.runtime.version"
                    action: delete
            exporters:
              signalfx:
                include_metrics:
                  - metric_names: [cpu.interrupt, cpu.user, cpu.system]
                  - metric_name: system.cpu.time
                    dimensions:
                      state: [interrupt, user, system]
                access_token: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}
                api_url: https://api.us1.signalfx.com
                correlation: null
                ingest_url: https://ingest.us1.signalfx.com
                sync_host_metadata: true
            service:
              pipelines:
                metrics:
                  exporters:
                  - signalfx
                  processors:
                  - memory_limiter
                  - batch
                  - resourcedetection
                  - resource
                  - resource/delete
                  - resource/add_environment
                  receivers:
                  - hostmetrics
                  - kubeletstats
                  - otlp
                  - receiver_creator
                  - signalfx
        secret:
          name: "splunk-otel-secret"
          create: false
          validateSecret: false
        splunkObservability:
          realm: us1
          profilingEnabled: true
        certmanager:
          enabled: false
          global:
            leaderElection:
              namespace: "cert-manager"
          installCRDs: false
        operator:
          enabled: true
          admissionWebhooks:
            certManager:
              certificateAnnotations:
                "helm.sh/hook": pre-install,post-upgrade
                "helm.sh/hook-weight": "1"
              issuerAnnotations:
                "helm.sh/hook": pre-install,post-upgrade
                "helm.sh/hook-weight": "1"
        distribution: gke/autopilot
        cloudProvider: gcp
```
