### ISSUE TITLE
Seeking simple example: scrape only logs in all running containers in any of 2 directories.  See how ChatGPT answered.

### ISSUE THREAD

**Issue by hectoralicea** [signalfx/splunk-otel-collector-chart#984]
Using the splunk-otel-collector-chart helm chart whats an example values.yaml might look like which would tell the otel collector to scrape only logs in all running containers in the following directories: `/var/jenkins_home/logs` and `/opt/applcation/logs`

We dont want to push anything else into splunk other than whats in these two directories`/var/jenkins_home/logs` and `/opt/applcation/logs`

Right now I'm pushing a ton of data other than what's  in these two logs.   These logs are not showing up.

BTW;  I asked chat gpt this question and it gave the following answer. Not sure how close this is, but I suspect its wrong because I cannot find the key `select_resources` anywhere in the documentation

```
otelcol:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      batch:
      - select_resources:
          logs: '/var/jenkins_home/logs/*.log'
        filter:
          config:
            include: ['*.log']
    exporters:
      splunk_hec:
        endpoint: "https://your-splunk-hec-endpoint"
        token: "your-splunk-hec-token"

```

**Comment by omrozowicz-splunk** [comment]
Hey, this config is unfortunately far from being correct 😅  
By default with Splunk Otel Collector Chart we collect all the logs from Kubernetes pods that match this pattern: `/var/log/pods/*/*/*.log`. The logs you want to collect don't match this pattern. If your goal is to collect only logs from `/var/jenkins_home/logs` and `/opt/application/logs` you can just disable the whole pipeline (with default filelog receiver) or exclude logs you don't need with:

```
agent:
  config:
    receivers:
      filelog:
         exclude:
            - /var/log/pods/*/*/*.log
```

Those missing files you can include in otel collector with `extraFileLogs`, here you have an example of how to do it: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/examples/only-logs-with-extra-file-logs/only-logs-with-extra-file-logs-values.yaml

**Comment by hectoralicea** [comment]
Thank you.  For those extra file logs, does it assume that those log locations are PVCs/PVs or can they be ephemeral storage in the pod.

**Comment by atoulme** [comment]
It doesn't know any better. The logs must be available to the process, how they're mounted is not visible to the process.

**Comment by gsmigelski** [comment]
Hey on this thread, similar to what you stated above about excluding logs, is this valid for finding logs (the included logs are extraVolumeMounts: with a mountPath: /var/jenkins_home/logs 

agent:
  config:
    receivers:
      filelog:
         exclude:
            - /var/log/pods/*/*/*.log
          include:
            -/var/jenkins_home/logs/audit-*.log

**Comment by gsmigelski** [comment]
> Hey, this config is unfortunately far from being correct 😅 By default with Splunk Otel Collector Chart we collect all the logs from Kubernetes pods that match this pattern: `/var/log/pods/*/*/*.log`. The logs you want to collect don't match this pattern. If your goal is to collect only logs from `/var/jenkins_home/logs` and `/opt/application/logs` you can just disable the whole pipeline (with default filelog receiver) or exclude logs you don't need with:
> 
> ```
> agent:
>   config:
>     receivers:
>       filelog:
>          exclude:
>             - /var/log/pods/*/*/*.log
> ```
> 
> Those missing files you can include in otel collector with `extraFileLogs`, here you have an example of how to do it: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/examples/only-logs-with-extra-file-logs/only-logs-with-extra-file-logs-values.yaml
 (see above coment)

**Comment by omrozowicz-splunk** [comment]
Hey @gsmigelski,
If I understand this right, you did something like:

```
agent:
  extraVolumes:
    - name: example-with-storage-logs
      hostPath:
        path: /var/jenkins_home/logs
  extraVolumeMounts:
    - name: example-with-storage-logs
      mountPath: /var/jenkins_home/logs
```

already?

If so, the way to gather all logs starting with `audit-`, ending with `.log` is to provide such config:

```
logsCollection:
  extraFileLogs:
    filelog/example-without-storage:
      include:
        - /var/jenkins_home/logs/audit-*.log
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.index: em_logs
        com.splunk.source: /var/jenkins_home/logs
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: example
``` 

`resource` part is not required, but I recommend setting it up - it will help to find the events in Splunk

**Comment by gsmigelski** [comment]
Ok yeah thats close. But the working code, since my volume is on the extraVolumeMount I needed to reference that here:
 "filelog/jenkins-logs-volume" . 


Here is a valid config with the reference to the mount named "jenkins-logs-volume"
`agent:
  extraVolumes:
    - name: jenkins-logs-volume
      persistentVolumeClaim:
        claimName: jenkins-pvc2
  extraVolumeMounts:
    - name: jenkins-logs-volume
      mountPath: /var/jenkins_home/logs  # Aligning mount point with the desired path
      readOnly: true
logsCollection:
  extraFileLogs:  
    filelog/jenkins-logs-volume:
      include: [/var/jenkins_home/logs/logs/*]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource: 
        com.splunk.source: /var/jenkins_home/logs
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: pvc-log`

Now i just need to put the exclude code back in so its to ignore the /var/log/pods: Where does this fit into this working config;
agent:
  config:
    receivers:
      filelog:
         exclude:
            - /var/log/pods/*/*/*.log

**Comment by omrozowicz-splunk** [comment]
`agent.config.receivers.filelog` will only overwrite the default `filelog` receiver. `filelog` and `fiellog/jenkins-logs-volume` are completely different data sources from OTel perspective.

**Comment by matthewmodestino** [comment]
Lol chatgpt 🙄. Still safe from the robots for now, I guess...

Fyi theres an easy way to disable the default log pipeline here:

```
logsCollection:

  # Container logs collection
  containers:
    enabled: true
```

That should disable the default container logging pipeline without needing to exclude.
